app = "synapse-mcp"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "9000"
  MCP_SERVER_URL = "https://synapse-mcp.fly.dev" 

[http_service.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 500

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/info"
  timeout = "5s"